
export const InternData = [
    {
        id: 1,
        no: "1",
        name: "Onah Sochima",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 5000,
    },
    {
        id: 2,
        no: "2",
        name: "Timothy Achonu",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "1",
        strike: 0,
        powerRanking: 2126,

    },
    {
        id: 3,
        no: "3",
        name: "Kizito Chinazo",
        avatar: 'avatars/avatar1.png',
        attendance: "93",
        bonus: "1",
        strike: 0,
        powerRanking: 2058,
    },
    {
        id: 4,
        no: "4",
        name: "Nkemdili Ezike",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 2053,
    },
    {
        id: 5,
        no: "5",
        name: "Charles Oriih",
        avatar: 'avatars/avatar1.png',
        attendance: "86",
        bonus: "0",
        strike: 1,
        powerRanking: 2043,
    },
    {
        id: 6,
        no: "6",
        name: "Chukwuka Edward",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 1,
        powerRanking: 2022,
    },
    {
        id: 7,
        no: "7",
        name: "Chinedu Ibelachi",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 2009,
    },
    {
        id: 8,
        no: "8",
        name: "Chimaobi Chukwuegbo",
        avatar: 'avatars/avatar1.png',
        attendance: "83",
        bonus: "0",
        strike: 0,
        powerRanking: 1982,
    },
    {
        id: 9,
        no: "9",
        name: "Chioma Ugwuodo",
        avatar: 'avatars/avatar1.png',
        attendance: "83",
        bonus: "0",
        strike: 0,
        powerRanking: 1996,
    },
    {
        id: 10,
        no: "10",
        name: "Onyinyechi Okeke",
        avatar: 'avatars/avatar1.png',
        attendance: "94",
        bonus: "0",
        strike: 0,
        powerRanking: 1943,
    },
    {
        id: 11,
        no: "11",
        name: "Jachike Victor",
        avatar: 'avatars/avatar1.png',
        attendance: "83",
        bonus: "0",
        strike: 0,
        powerRanking: 1930,
    },
    {
        id: 12,
        no: "12",
        name: "Samson Adersonmu",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 1980,
    },
    {
        id: 13,
        no: "13",
        name: "Ojumoola Akinyode",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 1978,
    },
    {
        id: 14,
        no: "14",
        name: "Daniel Ochi",
        avatar: 'avatars/avatar1.png',
        attendance: "88",
        bonus: "0",
        strike: 0,
        powerRanking: 1870,
    },
    {
        id: 15,
        no: "15",
        name: "John Okorie",
        avatar: 'avatars/avatar1.png',
        attendance: "74",
        bonus: "0",
        strike: 0,
        powerRanking: 1837,
    },
    {
        id: 16,
        no: "16",
        name: "Kenechukwu Chidume",
        avatar: 'avatars/avatar1.png',
        attendance: "93",
        bonus: "0",
        strike: 0,
        powerRanking: 1825,
    },
    {
        id: 17,
        no: "17",
        name: "Ebubechukwu Ezike",
        avatar: 'avatars/avatar1.png',
        attendance: "95",
        bonus: "0",
        strike: 0,
        powerRanking: 1822,
    },
    {
        id: 18,
        no: "18",
        name: "Emmanuel Nwafor",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 1821,
    },
    {
        id: 19,
        no: "19",
        name: "Goodnews Ofo",
        avatar: 'avatars/avatar1.png',
        attendance: "80",
        bonus: "0",
        strike: 0,
        powerRanking: 1817,
    },
    {
        id: 20,
        no: "20",
        name: "Amarachukwu Nweke",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 1817,
    },
]
