
export const InternData = [
    {
        id: 1,
        no: "1",
        name: "Onah Sochima",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 5000,
    },
    {
        id: 2,
        no: "2",
        name: "Timothy Achonu",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "1",
        strike: 0,
        powerRanking: 2500,

    },
    {
        id: 3,
        no: "3",
        name: "Kizito Chinazo",
        avatar: 'avatars/avatar1.png',
        attendance: "93",
        bonus: "1",
        strike: 0,
        powerRanking: 300,
    },
    {
        id: 4,
        no: "4",
        name: "Nkemdili Ezike",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 1700,
    },
    {
        id: 5,
        no: "5",
        name: "Charles Oriih",
        avatar: 'avatars/avatar1.png',
        attendance: "86",
        bonus: "0",
        strike: 1,
        powerRanking: 400,
    },
    {
        id: 6,
        no: "6",
        name: "Chukwuka Edward",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 1,
        powerRanking: 3000,
    },
    {
        id: 7,
        no: "7",
        name: "Chinedu Ibelachi",
        avatar: 'avatars/avatar1.png',
        attendance: "100",
        bonus: "0",
        strike: 0,
        powerRanking: 2550,
    },
    {
        id: 8,
        no: "8",
        name: "Chimaobi Chukwuegbo",
        avatar: 'avatars/avatar1.png',
        attendance: "83",
        bonus: "0",
        strike: 0,
        powerRanking: 1000,
    },
    {
        id: 9,
        no: "9",
        name: "Chioma Ugwuodo",
        avatar: 'avatars/avatar1.png',
        attendance: "83",
        bonus: "0",
        strike: 1,
        powerRanking: 1000,
    },
]
